
# Dosc about configuration: https://github.com/alacritty/alacritty

# Setup theme
# All available themes: https://github.com/alacritty/alacritty-theme?tab=readme-ov-file
import = ["~/.config/alacritty/themes/catppuccin_frappe.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }

decorations = "Buttonless"

opacity = 0.85
blur = true

startup_mode = "Windowed"

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 14
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = false

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true


[mouse]
hide_when_typing = true
