# Repo: https://github.com/alacritty/alacritty
# Dosc about configuration: https://alacritty.org/config-alacritty.html

# Setup theme
# All available themes: https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/catppuccin_frappe.toml"]

[env]
TERM = "xterm-256color"

[window]
# Use only predictable spacing
dynamic_padding = false
padding = { x = 10, y = 10 }

decorations = "Buttonless"

opacity = 0.85
blur = true

startup_mode = "Windowed"

[font]
size = 14
builtin_box_drawing = false

normal = { family = "MesloLGS Nerd Font", style = "Regular" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Beam", blinking = "Off" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true }
binding = { key = "U", mods = "Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
