# yamllint disable rule:line-length
# yamllint disable rule:comments
#
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
#
# Default config: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default
---
gui:
    windowSize: normal # normal is the best option
    language: en
    nerdFontsVersion: "3"
    skipDiscardChangeWarning: true
    skipStashWarning: true
    showRandomTip: false
    splitDiff: auto
    border: rounded
    commitLength:
        show: false
    showCommandLog: false
    showBottomLine: false
    showPanelJumps: false
    # Color attributes: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
    theme:
        activeBorderColor:
            - "#af38ff"
            - bold

keybinding:
    universal:
        prevItem-alt: k # go one line up
        nextItem-alt: l # go one line down
        prevBlock-alt: j # goto the previous block / panel
        nextBlock-alt: ; # goto the next block / panel
