# Doc: https://yazi-rs.github.io/docs/configuration/yazi
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[opener]
edit = [{ run = '$EDITOR "$@"', desc = "$EDITOR", block = true, for = "unix" }]

[manager]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5

[preview]
tab_size = 4
